name: flutter_base_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  flutter: 3.7.10
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  intl: any
  collection: any
  shared_preferences: 2.5.3
  uuid: ^4.5.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  async: ^2.13.0
  device_info_plus: ^11.4.0
  background_json_parser: ^1.0.6
  text_mask: ^1.0.4
  app_links: 6.4.0

  # Network
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  webview_flutter: ^4.11.0
  socket_io_client: ^2.0.3+1
  webview_flutter_wkwebview: ^3.20.0 # webview_flutter tarafından kullanılmakta ama son versiyon 3.18.0 olanda ios ta uygulamayı patlattığı için bu 3.17.0 versiyon sabitlendi daha sonra daha yeni versiyonlara geçilebilir
  cached_network_image: ^3.4.1
  android_id: ^0.4.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_local_notifications: ^19.1.0
  banner_image: ^1.0.9
  overlay_kit: ^1.1.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

  # State manager
  get: ^4.7.2

  # Error handler
  app_logger: ^0.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner:
  flutter_gen_runner:

dependency_overrides:
  async: ^2.8.2

flutter_gen:
  output: lib/app/constants/assets
  line_length: 120

  integrations:
    flutter_svg: true
  fonts:
    enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: GreycliffCF
      fonts:
        - asset: assets/fonts/GreycliffCF-Light.ttf
          weight: 300
        - asset: assets/fonts/GreycliffCF-Regular.ttf
          weight: 400
        - asset: assets/fonts/GreycliffCF-Medium.ttf
          weight: 500
        - asset: assets/fonts/GreycliffCF-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/GreycliffCF-Bold.ttf
          weight: 700