/// Proje içinde kullanılan padding ler
const double paddingXXXXS = 2;
const double paddingXXXS = 4;
const double paddingXXS = 6;
const double paddingXS = 8;
const double paddingS = 10;
const double paddingM = 15;
const double paddingL = 17;
const double paddingXL = 25;
const double paddingXXL = 30;
const double paddingXXXL = 35;
const double paddingXXXXL = 40;
const double paddingXXXXXL = 45;
const double paddingXXXXXXL = 50;
const double paddingXXXXXXXL = 55;

/// Proje içinde kullanılan radiusler
const double radiusXXXXXS = 3;
const double radiusXXXXS = 4;
const double radiusXXXS = 5;
const double radiusXXS = 6;
const double radiusXS = 8;
const double radiusS = 10;
const double radiusM = 15;
const double radiusL = 20;
const double radiusXL = 25;
const double radiusXXL = 30;
const double radiusXXXL = 40;
const double radiusXXXXL = 50;
