/// Proje içinde kullanılan padding ler
const double paddingXXXXXS = 2;
const double paddingXXXXS = 4;
const double paddingXXXS = 6;
const double paddingXXS = 8;
const double paddingXS = 10;
const double paddingS = 12;
const double paddingM = 15;
const double paddingL = 17;
const double paddingXL = 20;
const double paddingXXL = 24;
const double paddingXXXL = 30;
const double paddingXXXXL = 35;
const double paddingXXXXXL = 40;
const double paddingXXXXXXL = 45;
const double paddingXXXXXXXL = 50;
const double paddingXXXXXXXXL = 55;

/// Proje içinde kullanılan radiusler
const double radiusXXXXXXS = 3;
const double radiusXXXXXS = 4;
const double radiusXXXXS = 5;
const double radiusXXXS = 6;
const double radiusXXS = 8;
const double radiusXS = 10;
const double radiusS = 12;
const double radiusM = 15;
const double radiusL = 20;
const double radiusXL = 25;
const double radiusXXL = 30;
const double radiusXXXL = 40;
const double radiusXXXXL = 50;
